// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frmaukvlsbealmmzqsyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybWF1a3Zsc2JlYWxtbXpxc3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTY4MjksImV4cCI6MjA2MTc3MjgyOX0.z5Lp_6T6btGPVWRKt-yy069Qn11r1-HJ2ckm8Qufjyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);