// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmtsbdrmeohfoeibkglj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptdHNiZHJtZW9oZm9laWJrZ2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzA3ODQsImV4cCI6MjA2Nzg0Njc4NH0.sSx38fI9i-Ih_WFfkGveLFErCkAEhOxVc1w-7rwk5CQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});